language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-27

before_install:
  - yes | sdkmanager "platforms;android-27"

script:
    - ./gradlew testDebugUnitTest
